name: www.norte-a-sur.com
favicon: null
layout_spectrum: 0.8081
typography_spectrum: 0.9113
title: 'Norte A Sur '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fb4a54'
    - '#00baf5'
    - '#f0b1b8'
    - '#86ddf6'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
